input {
    # French AZERTY Layout
    kb_layout = fr
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    numlock_by_default = true

    follow_mouse = 1

    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        # The basics
        natural_scroll = false         # Mac-style inverted scrolling
        disable_while_typing = true    # Stops your palm from moving the mouse while coding
        tap-to-click = false           # Tap the pad to click (instead of physically pressing down)
        
        # Click behavior
        clickfinger_behavior = false   # 1-finger click = Left, 2-finger click = Right
        middle_button_emulation = false 
        
        # Feel and speed
        scroll_factor = 1.0            # Multiplier for scroll speed. Increase if scrolling feels sluggish.
        drag_lock = false              # If true, lifting your finger doesn't immediately drop the window you are dragging.
    }
}

# Per-device config for your specific hardware
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

misc {
    # Tells the Hyprland compositor itself to stop primary-pasting
    middle_click_paste = false
}
