DIR_PICTURES="~/images"
DIR_DOTFILES="~/dotfiles"
DIR_DOWNLOADS="~/downloads"
DIR_KEYS="~/keys"
DIR_MAILS="~/mails"
DIR_MOVIES="~/movies"
DIR_MUSICS="~/musics"
DIR_PROJECTS="~/projects"
DIR_SAVES="~/saves"
DIR_SCRIPTS="~/scripts"
DIR_VRAC="~/vrac"

DIR_THESIS="$DIR_PROJECTS/thesis"
DIR_WALLPAPERS="$DIR_PICTURES/wallpapers"
